### ISSUE TITLE
Newbie examples

### ISSUE THREAD

**Issue by marlev** [flammy/fsapi#1]
Awesome work.

As a total noob, I would like to request a demo page with buttons to: 
Settings (pin, ip)
power on/off 
Switch mode
Switch between presets
Control volume

**Comment by flammy** [comment]
Thanks for your response.

I will add a demo page in the next weeks.

**Comment by flammy** [comment]
I wrote a GUI for Controlling the device using this API, but I have to clean up the code before I put it on github.

**Comment by marlev** [comment]
👍 very interested to try it

**Comment by flammy** [comment]
I put the code into a different repo:

https://github.com/flammy/fsapi-remote
