### ISSUE TITLE
Get currently playing URI

### ISSUE THREAD

**Issue by tom08zehn** [flammy/fsapi#11]
Not really an issue but a question: I studied the docs but found nothing about it. **Is there a way to determine the currently playing URI** for mode 0 (webradio)? Either by querying the URI directly or getting it from the preset list?

I didn't find a GET-URL query for this task. From where do you know all the possible GET/SET-URLs? As far as I know there's no full documentation.

Thanks!

**Comment by flammy** [comment]
I have never seen a method for getting the URI from the API.

You are right there is no public documentation. I captured most of the Requests from the App or the Web-Gui and tried to document it [here](https://github.com/flammy/fsapi/blob/master/FSAPI.md).
