### ISSUE TITLE
Typos in some commands

### ISSUE THREAD

**Issue by QBJack** [flammy/fsapi#15]
You have some typos (double 'group' in url) here:

/fsapi/SET/netRemote.multiroom.group.group.addClient?pin=1337&value=[Device-udn]

should be (and works with)

/fsapi/SET/netRemote.multiroom.group.addClient?pin=1337&value=[Device-udn]

and here

/fsapi/SET/netRemote.multiroom.group.group.destroy?pin=1337&value=1

should be (and works with)

/fsapi/SET/netRemote.multiroom.group.destroy?pin=1337&value=1

Please update your documentation.

Thanks.
QBJack

**Comment by flammy** [comment]
Thank you for reporting, I fixed the typos.
